-- CREATE TABLE `meeting_rooms` (
--                                  `meeting_room_no`	BIGINT	NOT NULL	COMMENT 'auto increment',
--                                  `meeting_room_name`	VARCHAR(10)	NOT NULL	COMMENT 'Meeting A',
--                                  `meeting_room_capacity`	INT	NOT NULL
-- );
--
-- CREATE TABLE `bookings` (
--                             `booking_no`	BIGINT	NOT NULL	COMMENT 'auto increment',
--                             `meeting_room_no`	BIGINT	NOT NULL	COMMENT 'auto increment',
--                             `mb_no`	BIGINT	NOT NULL,
--                             `changes_no`	BIGINT	NULL	COMMENT 'auto increment',
--                             `booking_code`	VARCHAR(10)	NOT NULL	COMMENT 'Unique, UUID의 앞자리',
--                             `booking_date`	DATETIME	NOT NULL,
--                             `attendee_count`	INT	NOT NULL,
--                             `created_at`	DATETIME	NOT NULL,
--                             `finishes_at`	DATETIME	NULL
-- );
--
-- CREATE TABLE `booking_changes` (
--                                    `changes_no`	BIGINT	NOT NULL	COMMENT 'auto increment',
--                                    `changes_name`	VARCHAR(10)	NOT NULL	COMMENT '연장, 취소, 변경, 종료'
-- );
--
-- ALTER TABLE `meeting_rooms` ADD CONSTRAINT `PK_MEETING_ROOMS` PRIMARY KEY (
--                                                                            `meeting_room_no`
--     );
--
-- ALTER TABLE `bookings` ADD CONSTRAINT `PK_BOOKINGS` PRIMARY KEY (
--                                                                  `booking_no`
--     );
--
-- ALTER TABLE `booking_changes` ADD CONSTRAINT `PK_BOOKING_CHANGES` PRIMARY KEY (
--                                                                                `changes_no`
--     );
--
-- INSERT INTO `meeting_rooms` (`meeting_room_no`, `meeting_room_name`, `meeting_room_capacity`) VALUES
--                                                                                                   (1, 'Meeting A', 10),
--                                                                                                   (2, 'Meeting B', 20),
--                                                                                                   (3, 'Meeting C', 15);
-- INSERT INTO `booking_changes` (`changes_no`, `changes_name`) VALUES
--                                                                  (1, '연장'),
--                                                                  (2, '취소'),
--                                                                  (3, '변경'),
--                                                                  (4, '종료');
--
-- INSERT INTO `bookings` (
--     `booking_no`, `meeting_room_no`, `mb_no`, `changes_no`,
--     `booking_code`, `booking_date`, `attendee_count`, `created_at`, `finishes_at`
-- ) VALUES
--       (1, 1, 1001, NULL, 'ABC123', '2025-04-25 09:00:00', 8, '2025-04-20 10:00:00', NULL),
--       (2, 2, 1002, 1, 'DEF456', '2025-04-26 14:00:00', 12, '2025-04-21 11:00:00', '2025-04-26 16:00:00'),
--       (3, 3, 1003, 4, 'GHI789', '2025-04-27 10:00:00', 6, '2025-04-22 13:00:00', '2025-04-27 11:30:00');
